version: '2.2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      #- ./mysql-fistures:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=my_trello_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  mysql-data: